# cloudbuild.yaml - Monorepo Microservices + Frontend en Cloud Run

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: "the-respect-435301-u2"
  _REGION: "us-central1"
  _ARTIFACT_REPO: "monorepo-repo"
  _CLOUDSQL_INSTANCE: "the-respect-435301-u2:us-central1:monorepo-db"
  _VPC_CONNECTOR: "connector-1"
  _DB_NAME: "monorepo"
  _DB_USER: "postgres"
  _DB_PASSWORD_SECRET: "db-password" # Secret Manager name
  _BACKENDS: "security-audit purchases-suppliers tracking warehouse salesforce api-gateway cliente-web"

images:
  - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/security-audit'
  - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/purchases-suppliers'
  - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/tracking'
  - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/warehouse'
  - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/salesforce'
  - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/api-gateway'
  - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/cliente-web'

steps:
# ================================================
# Construcción y push de cada microservicio
# ================================================
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: "Build and Push Services"
  entrypoint: bash
  args:
    - -c
    - |
      set -e
      for svc in ${_BACKENDS}; do
        echo "🔨 Building $svc..."
        docker build -t us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${svc}:$SHORT_SHA ./backend/${svc^} 2>/dev/null || \
        docker build -t us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${svc}:$SHORT_SHA ./cliente_web

        echo "🚀 Pushing $svc..."
        docker push us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${svc}:$SHORT_SHA
      done

# ================================================
# Deploy en Cloud Run con conexión a Cloud SQL
# ================================================
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: "Deploy Services"
  entrypoint: bash
  args:
    - -c
    - |
      set -e
      DB_PASS=$(gcloud secrets versions access latest --secret=${_DB_PASSWORD_SECRET})

      for svc in ${_BACKENDS}; do
        echo "🚀 Deploying $svc..."
        gcloud run deploy $svc \
          --image us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${svc}:$SHORT_SHA \
          --platform managed \
          --region ${_REGION} \
          --allow-unauthenticated \
          --add-cloudsql-instances ${_CLOUDSQL_INSTANCE} \
          --vpc-connector ${_VPC_CONNECTOR} \
          --set-secrets DB_PASSWORD=${_DB_PASSWORD_SECRET}:latest \
          --set-env-vars DB_USER=${_DB_USER},DB_NAME=${_DB_NAME},DATABASE_URL="postgresql+psycopg2://${_DB_USER}:${DB_PASS}@/monorepo?host=/cloudsql/${_CLOUDSQL_INSTANCE}" \
          --memory=512Mi --cpu=1 --min-instances=0 --max-instances=3
      done
