[project]
name = "scripts-entregas"
version = "0.1.0"
description = "Generate non Jira charts: Velocity, Business Value, and Release Burndown"
readme = "README.md"
requires-python = ">=3.12.1"
dependencies = [
    "matplotlib>=3.10.7",
]
