name: Cliente Web Tests

on:
  push:
    paths:
      - 'cliente_web/**'
      - '.github/workflows/cliente-web-tests.yml'
  pull_request:
    paths:
      - 'cliente_web/**'
      - '.github/workflows/cliente-web-tests.yml'

jobs:
  tests:
    name: Cliente web tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cliente_web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare pnpm with Corepack
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate

      - name: Setup Node.js with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: cliente_web/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm test --if-present

      - name: Build project
        run: pnpm run build
